### ISSUE TITLE
clearCacheByRegex does not work with Local or Session storage

### ISSUE THREAD

**Issue by bryhemm** [nigrosimone/ng-http-caching#10]
When using Local or Session storage, clearCacheByRegex (and probably clearCacheByTag) does not work. It appears the loop in clearCacheByRegex is using a key that already contains the key prefix "NgHttpCaching::" and the implementation of delete in BrowserStorage is also prepending the same key prefix before attempting to delete the entry. This results in a failed attempt to delete "NgHttpCaching::NgHttpCaching::GET@/route" instead of  "NgHttpCaching::GET@/route" 

https://github.com/nigrosimone/ng-http-caching/blob/280cd1a9973d1e0e46f6ea526a81563c98d1837d/projects/ng-http-caching/src/lib/ng-http-caching.service.ts#L254

https://github.com/nigrosimone/ng-http-caching/blob/280cd1a9973d1e0e46f6ea526a81563c98d1837d/projects/ng-http-caching/src/lib/storage/ng-http-caching-browser-storage.ts#L94

**Comment by nigrosimone** [comment]
@bryhemm Fixed into 16.0.6 just published on NPM
