### ISSUE TITLE
Problem with asapScheduler

### ISSUE THREAD

**Issue by jbjhjm** [nigrosimone/ng-http-caching#12]
## Issue description

This is not an official bug report, because I am not 100% sure what is actually happening.
However, I experienced an issue in some situations, did some debugging and were able to find a solution to fix the problem.
I'm posting this here to let you know and do with it whatever you like.

So, for some requests, the request observable would never emit, if there was a cache hit.

Sometimes, when there was a cache hit, no response was emitted from this:

```ts 
scheduled(_of(cachedResponse.clone()), asapScheduler)
```

As stated above, it happens in some, but not in all situations, meaning I cannot add a reproduction unfortunately.

## observations

I found that the issue can be eliminated by not using `asapScheduler`.
I switched the scheduler to use `asyncScheduler` instead.

So here's some speculation on this.
I tap'd into the observable structure at many places and nothing of it would execute.

asapScheduler is said to emit very fast. I think what happens is that for some reason it emits BEFORE the subscriber is being added. As soon as I switched to asyncScheduler, all started working as expected.

##  proposed improvement

As an HttpRequest always is an async action, starting at the moment of subscription,
The cache response, stubbing HttpRequest, should imitate it as well as possible.
So I think there is good reason for not using asapScheduler but asyncScheduler. 

If I happen to find out more on this issue, I'll let you know here.

**Comment by nigrosimone** [comment]
Hi, thanks for the report, you're right. I fixed the problem in the newly released version 16.0.7.

**Comment by jbjhjm** [comment]
Thanks @nigrosimone , that was super-duper fast! 😀
