### ISSUE TITLE
`has` method in `NgHttpCachingBrowserStorage` has wrong type checking

### ISSUE THREAD

**Issue by FernandoX66** [nigrosimone/ng-http-caching#13]
In the `NgHttpCachingBrowserStorage` class, the `has` method is incorrectly checking the type of the returned value from the `getItem` method of the storage. When there is no item, it is checking if it is `undefined`, but checking the API of the `Storage` interface, this method returns `null`, causing the method to return true even if the element does not exist.

**Evidence:**

```
// lines 139-147 in ng-http-caching-browser-storage.ts
has(key: string): boolean {
  if (!key) {
    return false;
  }
  if (!key.startsWith(KEY_PREFIX)) {
      key = KEY_PREFIX + key;
  }
  return this.storage.getItem(key) !== undefined;
}
```

Return vale specification of the `has` method in the `Storage` interface (from MDN):

[Storage: getItem() method - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem)

`A string containing the value of the key. If the key does not exist, null is returned.`

**Comment by nigrosimone** [comment]
Hi, just fixed into version 16.0.10
