### ISSUE TITLE
`clearCache` method not working properly

### ISSUE THREAD

**Issue by FernandoX66** [nigrosimone/ng-http-caching#14]
I'm trying to delete all the cache from the session storage by using the `NgHttpCachingService` and calling the `clearCache` method, but when I use it, it doesn't clear all the cache. I think that the problem is in the `clear` method of the `NgHttpCachingBrowserStorage` class, since when you delete an item from the storage, the indexes change, and it doesn't delete all the items.

**Comment by nigrosimone** [comment]
Hi. Just fixed into version 16.0.11
