### ISSUE TITLE
edit cache lifetime of an already existing cache

### ISSUE THREAD

**Issue by filip-malinowski-rhebo** [nigrosimone/ng-http-caching#15]
I created a service that is kind of a controller for the NgHttpCachingService. This class implements more the less such methods
```ts
class Service {
  defaultCacheLifetime = 1000 * 60 * 60
  enabled$: Observable<boolean>
  header$: Observable<HttpHeaders>
  
  enable(): void
  disable(): void
  setLifetime(): void
}
```
so that I can use it later on in one component to let ther user manipulate default cache settings in the webapp.

Now the thing is...
In my `setLifetime()` it's fairly easy to change the lifetime for the future requests. However, I would like to be able to change the lifetime for the requests that were already stored in the cache store. Is there a way to do it with your lib? Putting aside if it's reasonable or not to do so 😅

**Comment by nigrosimone** [comment]
Hi! With the `NgHttpCachingService` you can get the cache store with `getStore()`. The store has:

```ts
    /**
     * Return the cache entry for the provided key.
     */
    get<K = any, T = any>(key: string): Readonly<NgHttpCachingEntry<K, T>> | undefined;

    /**
     * Set the cache entry for the provided key.
     */
    set<K = any, T = any>(key: string, value: NgHttpCachingEntry<K, T>): void;
```

eg:
```ts
import { NgHttpCachingService } from 'ng-http-caching';

export class Service {

  constructor(private ngHttpCachingService: NgHttpCachingService) {}

  setLifetime(): void {
    const key = 'GET@https://myapi';
    const store = this.ngHttpCachingService.getStore();
    const entry = store.get(key);
    if( entry ){
        store.set(key, {...entry, addedTime: Date.now()});
    }
  }
}
```

**Comment by filip-malinowski-rhebo** [comment]
Thank you! 🙇🏻
