### ISSUE TITLE
Cannot import provideNgHttpCaching

### ISSUE THREAD

**Issue by Cito** [nigrosimone/ng-http-caching#16]
I am following the README with v18.0.2, but cannot get past step 2.

When trying to `import { provideNgHttpCaching } from 'ng-http-caching'` I get an error message saying there is no such exported member. In fact among the published type info files [here](https://www.npmjs.com/package/ng-http-caching/v/18.0.2?activeTab=code), I would expect a `ng-http-caching-provider.d.ts` file, but it's missing.

Am I overlooking something?

**Comment by nigrosimone** [comment]
Hi, on GitHub there Is ready the version for Angular 19, full standalone, not published on npm. The npm version require tò import NgHttpCachingModule see npm docs

**Comment by Cito** [comment]
Ah ok, I understand. The README on GitHub will then be correct after v19 is published. Thanks for the quick response.

**Comment by nigrosimone** [comment]
Yep, Is for Angular 19! Coming soon!

**Comment by nigrosimone** [comment]
@Cito v. 19 was released https://www.npmjs.com/package/ng-http-caching
