### ISSUE TITLE
concurrency issues

### ISSUE THREAD

**Issue by tonyliving** [nigrosimone/ng-http-caching#4]
If there are two concurrent requests and the first request modifies the body, the second request will be modified at the same time. The expectation is not to modify the second request
![image](https://user-images.githubusercontent.com/7547210/211456397-c97b65ac-a2cd-4769-8997-0a0f2e34a44b.png)

**Comment by nigrosimone** [comment]
This is the expected behaviour. You need to clone the body of the response before modifies the body, because the response object is stored in memory. The library for performance reasons return always the same reference to the cached response.
