### ISSUE TITLE
No more working with Anguar 15

### ISSUE THREAD

**Issue by lilas78** [nigrosimone/ng-http-caching#6]
We have implemented the HTTP caching with angular 14 and ng-http-caching module. Everything wrorked fine.

After upgrading to Angular 15.2.4 and to ng-http-caching  15.0.2, the same code is not working anymore.

Here is the code where we make the http request :

`const output = await lastValueFrom(this.httpClient.get<boolean>(url, CACHING_OPTIONS);`

The case which is not working is the following :

-  make a first request and receive the response from the server => everything is fine, the Promise from 'lastValueFrom' is resolved
- make another same request => the Promise is never resolved and async call gets stucked.

Is there any changes in the way to use   ng-http-caching module and angular 15  ?

**Comment by nigrosimone** [comment]
Hi, I have tried with await and seems works https://stackblitz.com/edit/demo-ng-http-caching-jhivld?file=src%2Fapp%2Fapp.component.ts

can you replicate the problem on stackblitz?

**Comment by lilas78** [comment]
https://stackblitz.com/edit/demo-ng-http-caching-hznm8b?file=src/app/app.component.ts

Systematically, just after starting the app, 

- first call => response from the server, OK
- second call => no response (time is left blank in the html) KO
- call afterwards => OK, value got from the cache

This is not reproduced after clearing the cache. Only after ng serve

**Comment by lilas78** [comment]
And I also reproduce the problem when requests are queued (and this time, not only the first time after ng serve, but each time). But I don't know how to reproduce it in Stackblitz (how can I delay the server response)

**Comment by nigrosimone** [comment]
@lilas78 sorry for the late. I have debugged a lot the problem and finally I found the problem. I think is a rxjs bug and I have opened a issue https://github.com/ReactiveX/rxjs/issues/7241 (also on stackoverflow https://stackoverflow.com/questions/75906191/rxjs-lastvaluefrom-scheduled-asapscheduler-strange-behaviour) . Meanwhile I have released the 15.0.**3** with a workaround that fix the problem.

**Comment by lilas78** [comment]
@nigrosimone  Thank you so much for this fix and this new release. It seems to work for me (even if in the provided stackblitz, there is is still the very first call after ng serve which doesn't get any answer).

**Comment by nigrosimone** [comment]
@lilas78 I can't reproduce the issue "very first call after ng serve"  :-(

**Comment by lilas78** [comment]
I click on the link you gave me

https://stackblitz.com/edit/demo-ng-http-caching-jhivld?file=src%2Fapp%2Fapp.component.ts

On the preview part of the screen, the message "starting dev server"
appears, then your screen appears.  Click once on the button "execute
request" -> ok.  Click a second time -> no answer.   After that, it's ok.

Reproduced each time I reload this page.

Le mar. 4 avr. 2023 à 08:18, Nigro Simone ***@***.***> a
écrit :

**Comment by lilas78** [comment]
And this fix doesn't fix the problem when calls are queued (not cached).
Do you know how I can reproduce this case in Stackblitz (how can I delay the server response to make queued calls) ?

**Comment by nigrosimone** [comment]
> On the preview part of the screen, the message "starting dev server"
> appears, then your screen appears.  Click once on the button "execute
> request" -> ok.  Click a second time -> no answer.   After that, it's ok.
> 

@lilas78 I have upgrade the lib at version 15.2.1 and works https://stackblitz.com/edit/demo-ng-http-caching-jhivld?file=src%2Fapp%2Fapp.component.ts

> And this fix doesn't fix the problem when calls are queued (not cached).
> Do you know how I can reproduce this case in Stackblitz (how can I delay the server response to make queued calls) ?

The only way is call a custom endpoint with some slow REST API
