### ISSUE TITLE
Incorrect response caching / fetching

### ISSUE THREAD

**Issue by vigneshvaid** [nigrosimone/ng-http-caching#7]
With the current implementation while caching the response in the body the whole response is stored on line 39: [https://github.com/nigrosimone/ng-http-caching/blob/master/projects/ng-http-caching/src/lib/storage/ng-http-caching-browser-storage.ts](url)

`export const serializeResponse = (res: HttpResponse<any>): string => {
    const response = res.clone();
    return JSON.stringify({
        headers: Object.fromEntries( // Just a helper to make this into an object, not really required but makes the output nicer
            response.headers.keys().map( // Get all of the headers
                (key: string) => [key, response.headers.getAll(key)] // Get all of the corresponding values for the headers
            )
        ),
        status: response.status,
        statusText: response.statusText,
        url: response.url,
        body: response // Serialize the body, all well and good since we are working on a clone
    });
}`

whereas while fetching the response from cache the whole response is shared as part of body on line 63: [https://github.com/nigrosimone/ng-http-caching/blob/master/projects/ng-http-caching/src/lib/storage/ng-http-caching-browser-storage.ts](url)

`export const deserializeResponse = <T = any>(res: string): HttpResponse<T> => {
    const response = JSON.parse(res);
    return new HttpResponse<T>({
        url: response.url,
        headers: new HttpHeaders(response.headers),
        body: response.body,
        status: response.status,
        statusText: response.statusText,
    });
}`

Proposed Fix:

Store only body in the cached content on line 39 as shown below

`export const serializeResponse = (res: HttpResponse<any>): string => {
    const response = res.clone();
    return JSON.stringify({
        headers: Object.fromEntries( // Just a helper to make this into an object, not really required but makes the output nicer
            response.headers.keys().map( // Get all of the headers
                (key: string) => [key, response.headers.getAll(key)] // Get all of the corresponding values for the headers
            )
        ),
        status: response.status,
        statusText: response.statusText,
        url: response.url,
        body: response.body // Serialize the body, all well and good since we are working on a clone
    });
}`

**Comment by nigrosimone** [comment]
Thanks, you are right! fixed in 15.2.2

**Comment by vigneshvaid** [comment]
@nigrosimone can you release this fix for v14?

**Comment by nigrosimone** [comment]
no plan to upgrade your app to Angular 15? Angular 16 it's coming. Currently I only manage the current version into my library. 
PS the upgrade from 14 to 15 is absolutely safe.

**Comment by vigneshvaid** [comment]
Ohh okay. Angular 15 upgrade is not yet finalized by team but yeah will still try out with v15
