### ISSUE TITLE
nested call bug

### ISSUE THREAD

**Issue by tonyliving** [nigrosimone/ng-http-caching#8]
Nested requests will request multiple times，
I modified the getRequest method.You can click "EXECUTE REQUEST", and you can see two db requests in the developer tools
[https://stackblitz.com/edit/demo-ng-http-caching-fgm53y](https://stackblitz.com/edit/demo-ng-http-caching-fgm53y)

**Comment by nigrosimone** [comment]
Hi @tonyliving, sorry for the late.
The bug is fixed in the 15.2.3 version

https://stackblitz.com/edit/demo-ng-http-caching-t3xzwv?file=src%2Fapp%2Fapp.component.ts

**Comment by tonyliving** [comment]
@nigrosimone 
I added console.log('1') at line 66
Added console.log('2') on line 86
But the first time you click "EXECUTE REQUEST", the console will only output 1

[https://stackblitz.com/edit/demo-ng-http-caching-vzqerf?file=src%2Fapp%2Fapp.component.ts%3AL66](https://stackblitz.com/edit/demo-ng-http-caching-vzqerf?file=src%2Fapp%2Fapp.component.ts%3AL66)

**Comment by nigrosimone** [comment]
Ops! My mistake! re-fixed in 15.2.4

https://stackblitz.com/edit/demo-ng-http-caching?file=src%2Fapp%2Fapp.component.ts
