### ISSUE TITLE
NgHttpCachingBrowserStorage based storage does not work correctly

### ISSUE THREAD

**Issue by bryhemm** [nigrosimone/ng-http-caching#9]
When I try to configure ng-http-caching to use Local or Session storage, the cache is being populated, but the results are never served from the cache. A new HTTP request is always triggered.

I believe its because the 'version' field is not being set when writing to the cache.
https://github.com/nigrosimone/ng-http-caching/blob/72b896306d36abee0b28b2ec90ac51d225b7cd23/projects/ng-http-caching/src/lib/storage/ng-http-caching-browser-storage.ts#L131

**Comment by nigrosimone** [comment]
Hi, thanks! I have fixed in 16.0.5 just published on NPM. Now, it works as expected?

**Comment by bryhemm** [comment]
Thanks, it works now.
